version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10  # lub inny obraz z dockerem
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Buduj i wypchnij obraz Docker
          command: make docker_push

workflows:
  version: 2
  build-and-push:
    jobs:
      - build

steps:
  - checkout
  - run: make docker_build